### PR TITLE
Fix: Add missing closing div tag in Home component

### PR DESCRIPTION
**Pull request by Himess**
This commit fixes an issue in the Home component where a closing div tag was missing, causing potential rendering issues and violating proper HTML structure. The missing tag was added to the nested layout within the IpProvider component, ensuring proper component rendering and maintaining code quality.

Changes:
- Added the missing </div> closing tag inside the IpProvider component in Home.tsx.

This fix ensures that the Home component adheres to correct syntax, avoids runtime rendering errors, and aligns with project coding standards.

### CODE REVIEW

**Comment by MelodyFish** [comment]
div tag is not miss, just wrong with the div tag indentation. I have modified it. Please see for details at this[ pr](https://github.com/storyprotocol/storykit/pull/82)

**Comment by MelodyFish** [comment]
the div tag is not missing, just wrong with div tag indentation, I had fixed it last week. Please see for this [pr](https://github.com/storyprotocol/storykit/pull/82)

**Comment by MelodyFish** [comment]
the div tag is not missing, just a wrong with div tag  indentation. I have fixed it last week. Please see for this [pr](https://github.com/storyprotocol/storykit/pull/82).

**Comment by Himess** [comment]
Thank you

**Pull request closed without merging**
